config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about' ,as: 'about'
  resources :users, only: [:show, :index, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_one_attached :profile_image
    def get_profile_image(width, height)
    unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:about, :top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id =book.id
    comment.save
    redirect_to book_path(book.id)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end

  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = User.find(current_user.id)
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(current_user.id)
    if current_user != @book.user
      @books = Book.all
      redirect_to books_path
    end
  end

  def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id)
       flash[:success] = "You have updated book successfully."
    else
      @user = User.find(current_user.id)
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book_favorite = current_user.favorites.new(user_id: current_user.id, book_id: params[:book_id])
    @book_favorite.save
    redirect_to request.referer
  end
  def destroy
    @book_favorite = current_user.favorites.find_by(user_id: current_user.id, book_id: params[:book_id])
    @book_favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  


  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :index, :show]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      @books = @user.books
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">


<h1>Editing Book</h1>

      <% if @book.errors.any? %>
      <% if @book.errors.count > 1 %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <% else %>
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <% end %>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
      <% end %>
<%= form_with model: @book do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title, class: "form-control book_title" %>
</div>
<div class="form-group">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class: "form-control book_body" %>
</div>
<div class="form_group">
  <%= f.submit "Update Book", class: "btn-success btn"%>
</div>

<% end %>

<p><%=link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %></p>

</div>
</div>
</div>
</main>

app/views/books/index.html.erb
<main>

<p id="notice"></p>
<div class="container px-5 px-sm-0">
      <% if @book.errors.any? %>
      <% if @book.errors.count > 1 %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <% else %>
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <% end %>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
      <% end %>

  <div class="row">

    <%= render "/users/main", user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <div>
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= link_to user_path(book.user_id) do %>
                 <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete, class:"text-danger" do %>
                <i class="fa-solid fa-heart"> <%= book.favorites.count %></i>

                <% end %>
                <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fa-solid fa-heart"> <%= book.favorites.count %></i>

                <% end %>
              <% end %>
              </td>
              <td> <%= "コメント数: #{book.book_comments.count}" %></td>
           </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
</main>

app/views/books/new.html.erb
      <div>
        <h2 class="mt-3">New Book</h2>
        <%= form_for Book.new do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <button class="btn btn-success commit" type="submit">Create Book</botton>
        </div>
        <% end %>
      </div>

app/views/books/show.html.erb
<main>
  <%=  flash[:success] %>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

<%= render "/users/main", user: @book.user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <div>
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td><%= image_tag @book.user.get_profile_image(80,80) %><br>
              <%= link_to @book.user.name, user_path(@book.user.id) %></td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
              <td><a class="btn btn-sm btn-success", href="<%= edit_book_path(@book.id) %>">Edit</a></td>
              <td><a class="btn btn-sm btn-danger" href="<%= book_path(@book) %>" data-method="delete">Destroy</a></td>
              <% end %>
              <td><% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete, class:"text-danger" do %>
                <i class="fa-solid fa-heart"> <%= @book.favorites.count %></i>

                <% end %>
                <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                <i class="fa-solid fa-heart"> <%= @book.favorites.count %></i>

                <% end %>
              <% end %></td>
              <Td><p>コメント数: <%= @book.book_comments.count %></p>

           </tr>
          </tbody>

        </table>
        <% @book.book_comments.each do |book_comment| %>
        <table>
          <td><%= image_tag book_comment.user.get_profile_image(80,80) %><br>
          <%= link_to book_comment.user.name, user_path(book_comment.user) %></td>
          <td><%= book_comment.comment %></td>
          <% if book_comment.user == current_user %>
          <td>
            <%= link_to book_book_comment_path(@book, book_comment), method: :delete, class:"btn btn-sm btn-danger" do%>
            Destroy
            <% end %>
          </td>
          <% end %>
        </table>
        <% end %>
        <div>
          <%= form_with model: [@book, @book_comment] do |f| %>
            <%= f.text_area :comment, rows: '5', class: "col-md-12" %>
            <%= f.submit "送信" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="px-3 mx-auto">
          <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions, impressions, and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0d85ef1dd6.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <%= link_to root_path, class:"navbar-brand" do %>
            Bookers
          <% end %>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
            <%= link_to users_path, class:"nav-link text-light" do %>
              <i class="fas fa-users"></i>Users
            <% end %>
            <%= link_to books_path, class:"nav-link text-light" do %>
              <i class="fas fa-book-open"></i>Books
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i>Logout
            <% end %>

            <% else %>
            <%= link_to root_path, class:"nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
            <%= link_to about_path, class:"nav-link text-light" do %>
              <i class="fas fa-link"></i>About
            <% end %>
            <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
              <i class="fas fa-user-plus"></i>sign up
            <% end %>
            <%= link_to new_user_session_path, class:"nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i>Login
            <% end %>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <% if notice %>
      <p class="notice"><%= notice %></p>
      <% end %>

    <%= yield %>
     <footer>
        <div class="container mt-5">
          <div class="row">
            <div class="mx-auto">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
      </footer>
  </body>
</html>

app/views/users/_main.html.erb
    <div class="col-md-3">


      <div class="user_info">
        <h2>User info</h2>
        <%= image_tag user.get_profile_image(100,100) %><br>
        <table class="table">
          <tr></tr>
          <tr>
            <th>name</th><th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th><th><%= user.introduction %></th>
          </tr>
        </table>
        <div class="row">
          <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
      </div>

      <div>
        <h1 class="mt-3">New book</h1>
        <%= form_for Book.new do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <button class="btn btn-success commit" type="submit">Create Book</botton>
        </div>
        <% end %>
      </div>
    </div>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
        

<h2>User info</h2>
      <% if @user.errors.any? %>
      <% if @user.errors.count > 1 %>
      <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
      <% else %>
      <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
      <% end %>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
      <% end %>
<%= form_with model: @user do |f| %>
<div class="form-group">
  <label for="user_name">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", class: "form-control name" %>
</div>
<div class="form-group">
  <label for="user_image">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", class: "form-control-file user_image" %>
</div>
<div class="form-group">
  <label for="user_introduction">Introduction</label>
  <%= f.text_area :introduction, class: "form-control introduction"%>
</div>
<div class="form_group">
  <%= f.submit "Update User", class: "btn-secondary btn"%>
</div>
<% end %>
</div>
</div>
</div>
</main>

app/views/users/index.html.erb
<main>

<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render "/users/main", user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <div>
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= image_tag user.get_profile_image(80,80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
           </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
</main>

app/views/users/show.html.erb
<main>

  <%= flash[:success] %>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render "/users/main", user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <div>
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= link_to user_path(book.user_id) do %>
                 <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete, class:"text-danger" do %>
                <i class="fa-solid fa-heart"> <%= book.favorites.count %></i>

                <% end %>
                <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fa-solid fa-heart"> <%= book.favorites.count %></i>

                <% end %>
              <% end %></td>
              <td> <%= " コメント数: #{book.book_comments.count}" %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
</main>